# Generated by Django 5.0.2 on 2024-02-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='post_name',
            field=models.CharField(default='Default Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='post_text',
            field=models.CharField(max_length=5000),
        ),
    ]
