# Generated by Django 5.0.2 on 2024-02-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_question_post_name_alter_question_post_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Post',
        ),
    ]
